GCSERP/GCSERP.MVC/Controllers/ProdutoController.cs
using AutoMapper;
using GCSERP.MVC.Models;
using GCSERP.Produtos.Entidades.Classes;
using GCSERP.Produtos.Entidades.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace GCSERP.MVC.Controllers
{
    [Authorize]
    public class ProdutoController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IRepositorioProdutos _repositorioProdutos;
        private readonly IRepositorioProdutosClassificacoes _repositorioProdutosClassificacoes;

        public ProdutoController(IMapper mapper, 
            IRepositorioProdutos repositorioProdutos,
            IRepositorioProdutosClassificacoes repositorioProdutosClassificacoes)
        {
            _mapper = mapper;
            _repositorioProdutos = repositorioProdutos;
            _repositorioProdutosClassificacoes = repositorioProdutosClassificacoes;
        }

        //[HttpGet("")]
        [HttpGet("/produto/index")]
        [HttpGet("/produto/listar-produtos")]
        public async Task<IActionResult> Index()
        {
            var produtos = await _repositorioProdutos.ObterTodosAsync();
            var produtosVM = ProdutoViewModel.DelvoverListaVM(_mapper, produtos);

            return View(produtosVM);
        }

        // GET: ProdutoClassificacao/detalhar/5
        [HttpGet("/produto/informacoes/{id}")]
        [HttpGet("/produto/detalhar/{id}")]
        public async Task<ActionResult> Detalhar(int id)
        {
            var produto = await _repositorioProdutos.ObterAsync(id);
            var produtoVM = ProdutoViewModel.DevolverProdutoVM(_mapper, produto);

            return View(produtoVM);
        }

        // GET: ProdutoClassificacao/novo
        [HttpGet("/produto/novo")]
        [HttpGet("/produto/criar")]
        [HttpGet("/produto/inserir")]
        public async Task<ActionResult> Criar()
        {
            var classificacoes = await _repositorioProdutosClassificacoes.ObterTodosAtivosAsync();
            ProdutoViewModel vm = ProdutoViewModel.Instanciar(classificacoes);

            return View(vm);
        }

        // POST: ProdutoClassificacao/novo
        [HttpPost("/produto/novo")]
        [HttpPost("/produto/criar")]
        [HttpGet("/produto/inserir")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Criar(ProdutoViewModel produtoViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                if (produtoViewModel.Validar())
                {
                    Produto produto = produtoViewModel.Produto();
                    _repositorioProdutos.Adicionar(produto);
                    await _repositorioProdutos.UOW.CommitAsync();
                } 
                else
                {
                    ModelState.AddModelError(string.Empty, "Dados inválidos!");
                    return await Criar();
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProdutoClassificacao/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProdutoClassificacao/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //// GET: ProdutoClassificacao/Delete/5
        //public ActionResult Apagar(int id)
        //{
        //    return View();
        //}

        // DELETE: Produto/apagar/5
        [HttpDelete("/produto/apagar/{id}")]
        [HttpDelete("/produto/remover/{id}")]
        [HttpDelete("/produto/deletar/{id}")]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Apagar(int id)
        {
            try
            {
                var produto = await _repositorioProdutos.ObterAsync(id);
                produto.Apagar();
                _repositorioProdutos.Atualizar(produto);
                await _repositorioProdutos.UOW.CommitAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet("/produto/abrir-classificacoes")]
        public async Task<IActionResult> AbrirClassificacao()
        {
            var produtos = await _repositorioProdutos.ObterTodosAsync();
            var produtosVM = ProdutoViewModel.DelvoverListaVM(_mapper, produtos);            

            return View(produtosVM);
        }
    }
}

GCSERP/GCSERP.MVC/Views/Shared/_CSSPartial.cshtml
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

<link rel="stylesheet" href="~/css/site.css" />

GCSERP/GCSERP.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GCSERP.MVC</title>

    <!--
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    -->
    <partial name="_CSSPartial" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GCSERP.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LayoutLogin" />

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CadastroUsuarios">Cadastro de Usuários</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Cadastro de Produtos</a>
                        </li>                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GCSERP.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <partial name="_ScriptsPartial" />
    <!--
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GCSERP/GCSERP.MVC/Views/Shared/_LayoutLogin.cshtml
<ul class="navbar-nav">
    @if (Context.User.Identity.IsAuthenticated)
    {
        <li class="nav-item">
            <a class="nav-link text-dark">@Context.User.Identity.Name</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-red" asp-area="" asp-controller="Home" asp-action="Sair">Sair</a>
        </li>
        <li class="nav-item">
            <a class="nav-link btn btn-primary" asp-area="" asp-controller="Home" asp-action="Registrar">Criar Usuário</a>
        </li>
    }
    else
    {
        <li class="nav-item" style="padding-right: 30px;">
            <a class="btn btn-primary" asp-area="" asp-controller="Home" asp-action="entrar">Entrar</a>
        </li>
    }
</ul>

GCSERP/GCSERP.MVC/Views/Shared/_ScriptsPartial.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Bootstrap 4 dependency -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/js/bootstrap.bundle.min.js"></script>

<!-- bootbox code -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js"></script>
<!--
<script src="bootbox.locales.min.js"></script>
-->

<script src="~/js/site.js" asp-append-version="true"></script>